const ALERTS_REQUEST_END = 'ALERTS_REQUEST_END'
const ALERTS_REQUEST_ERROR = 'ALERTS_REQUEST_ERROR'
const ALERTS_REQUEST_START = 'ALERTS_REQUEST_START'

module.exports = {
  ALERTS_REQUEST_END,
  ALERTS_REQUEST_ERROR,
  ALERTS_REQUEST_START
}
